### ISSUE TITLE
【AWSリモート研修環境】ハンズオン中にストレージサイズが足りなる

### ISSUE THREAD

**Issue by imagepit** [MinamiSakamotoIppei/imagepit#10]
## 概要

AWSリモート研修環境にてハンズオン中にストレージサイズが足りなくなった。

2024年12月19日に開催したオープン研修マイクロサービスアーキテクチャ入門研修にてリモート研修環境のストレージサイズが不足していることにより次のような問題が発生した。

- `docker compose up`コマンドを実行した際に次のようなエラーが発生した。

_エラーメッセージ_
```
No space left on device
```

## 解決策

**AWSリモート研修環境構築時にストレージのサイズを8GBに設定していたが、このサイズでは不十分であることがわかった。**

そこで、ストレージのサイズを20GBに変更することで解決する。

**Comment by imagepit** [comment]
## 対応連絡

当方にてリモート環境構築時のプログラムを修正し、ストレージサイズを20GBにするよう改善しましたのでお知らせします。

- **※ なおこの修正によって、運用側での手順変更は発生していません。** （今までどおりリモート研修環境構築用のGitHub Issueにコメントを追加するのみです。）

**Comment by MinamiSakamotoIppei** [comment]
的確に問題を解決いただき、ありがとうございました。
当社髙橋とも状況を確認いたしました。

**Comment by imagepit** [comment]
ご連絡ありがとうございます。それでは本件はクローズいたします。
