### ISSUE TITLE
顧客側で研修環境準備する場合の運用改善

### ISSUE THREAD

**Issue by imagepit** [MinamiSakamotoIppei/imagepit#3]
2024年11月26日実施のひたちなかテクノセンターでの「セキュアプログラミング」の研修において次のインシデントが発生しましたので、顧客側による研修環境準備をする場合の運用を改善をご検討ください。

## 背景

- 一部の受講者の端末にてDockerがインストールされていない事が判明し、講師側でインストールを試みたがUbuntuのパスワードがわからず、インストールができなかった。
- フルネスの運用側に確認しても、今回の研修はひたちなかテクノセンター側が準備したので、フルネス側ではUbuntuのパスワードを把握していない。
- 顧客側も特に重要な情報との把握をしていなかったので結局、設定したUbuntuのパスワードを誰もしならい状態だった。

そのため、研修の進行が遅れる事態となりました。結果的には講師が昼休み中に、対象の受講者のWSL環境を再作成してDockerをインストールすることで解決しました。

## 先日のお打合せでのやりとり

昨日のお打合せでフルネス側では次のような改善案を検討されたと伺っています。

- **今後は原則、客先訪問での研修実施においても「リモート研修環境」で構築することにより今回の事象が発生しないようにする**

上記の方針で問題ないと思います。
が、上記の改善案では、顧客側がどうしても研修環境を客先で準備したい場合に困ると思います。
（顧客満足低下や機会損失の要因にもなりかねないと考えます）

そのため、**顧客側による研修環境準備をお願いする場合の運用も整理しておく必要がある**と考えています。

## 運用改善案

- **顧客側で環境構築する場合には、フルネス側での把握しておいたほうがいい設定内容（今回だったらUbuntuのパスワード情報）を事前に共有してもらうように客先に依頼する**

これにより、リモート環境での研修実施と同様になにか問題が発生した場合にも、迅速に対応できるようになると考えます。

**Comment by MinamiSakamotoIppei** [comment]
ご指摘ありがとうございます。

> 顧客側で環境構築する場合には、フルネス側での把握しておいたほうがいい設定内容（今回だったらUbuntuのパスワード情報）を事前に共有してもらうように客先に依頼する
> これにより、リモート環境での研修実施と同様になにか問題が発生した場合にも、迅速に対応できるようになると考えます。

この点、社内スタッフと共有いたしました。
次回以降安心いただけるようにいたします。

**Comment by imagepit** [comment]
了解しました。ありがとうございます。

**Comment by imagepit** [comment]
リモート研修環境およびローカルでの環境の構築手順を少し修正しました。

**＜修正内容＞
 環境構築コマンドの中にsudoコマンドでもUbuntuのパスワードを求められないようにしました。
※この対応により、研修中（ハンズオン）でUbuntuパスワードを入力する必要がなくなりました。**

＜背景＞
※AWSのリモート研修環境を構築していくなかでEC2はそもそもsudoコマンドでUbuntuパスワードを求められないので、それでその設定を入れればいいと気づき対応しました。

＜今後の運用の変更点＞
運用側では受講者に連絡する際にUbuntuパスワードを記載する必要がない、ということになります。
なので、先日のひたちなかの研修のようにローカル端末に環境を構築する場合にも客先からUbuntuのパスワードを確認する必要はなくなりました。
早く気づけばよかったです。（すみません）

いずれにしても、今後は客側でローカル端末に環境を構築する際は常にフルネス側で押さえておくべき情報はないかは留意してもらえればと思います。
（今のところそういった情報は私の環境構築にはないですが。。）

## 手順変更点

ちなみに手順書で変更した箇所はこちらです。setup-remote2.shからsetup-remote3.shに変更しています。

![image](https://github.com/user-attachments/assets/aefd547f-c78c-4cb7-900c-b4bfdd1debd8)

ローカルでの環境構築手順も次の箇所を変更しました。

<img width="668" alt="image" src="https://github.com/user-attachments/assets/23ca48e8-4b16-4e4d-a2e1-a93e1fad12f8">

**Comment by MinamiSakamotoIppei** [comment]
ありがとうございます！
AWS対応、いいことずくめですね。すばらしい。

井上が本日体調を崩して休んでいるなど、
今週は多忙なSO陣が検討に時間がとれておりません。
週明けに髙橋が主体となって、AWS導入開始時期について検討を進めます。

引き続きよろしくお願いいたします。

**Comment by MinamiSakamotoIppei** [comment]
綿密に準備いただいたAWS環境にて、
研修開催が成功（2024年12月19−20日）し、
こちらの内容は概ね解決したと理解しております。

> いずれにしても、今後は客側でローカル端末に環境を構築する際は常にフルネス側で押さえておくべき情報はないかは留意してもらえればと思います。
> （今のところそういった情報は私の環境構築にはないですが。。）

事前の接続確認テストはこれまで通りいたします。

> 顧客側で環境構築する場合には、フルネス側での把握しておいたほうがいい設定内容（今回だったらUbuntuのパスワード情報）を事前に共有してもらうように客先に依頼する

ひたちなかの今回の研修を開催する場合は、
基本的にAWSを利用を、営業側から提案することで、
同様の事象は回避できると考えています。

**Comment by imagepit** [comment]
ご連絡ありがとうございます。了解しました。本件はクローズいたします。
