### ISSUE TITLE
【LTRE経由研修】受講者アンケートの質問解答運用整理

### ISSUE THREAD

**Issue by imagepit** [MinamiSakamotoIppei/imagepit#7]
## 概要

LTRE経由の研修の受講者アンケート運用について整理し、初日アンケートで質問事項があった場合に講師が2日目にスムーズに対応できるようにする。

## 背景

2024年12月4日実施のLTRE経由の研修（ドメイン駆動設計基礎）で、受講者アンケートの運用について、講師が初日アンケートを確認する運用を把握していなかったので、講師が2日目の昼休みに質問内容を確認して対応した。できれば初日のアンケート内容は初日に講師が確認できるようにして、2日目の講義開始時に質問内容を確認できるようにしたい。

- LTRE様の研修では例年、研修前、初日、2日目の3回に分けてアンケートを実施している
- そのためチェックシートには事前アンケート（研修前）と受講者アンケート（初日、2日目）に項目を分けて記載をしておりましたかえって分かりづらいご案内になっている
- 2日目にアンケートの内容に対してご回答いただく点についても事前案内が不足していた

## 改善案

- 初日のアンケート内容を講師が確認できるようにする。
  - 事前のチェックシートにアンケート結果を確認できるURLを記載する。
  - 2日目の講義開始時に質問内容解答する運用をチェックシートに記載する。

**Comment by MinamiSakamotoIppei** [comment]
事態を整理してくださって、ありがとうございます。
現場スタッフとも確認・検討し、今後は以下の２つの対策を進める予定です。

### 改善案１
* チェックシートの構成を修正して、**1日目のアンケート結果のURLを確認いただきやすい表記にする**
* **2日目の朝の事務局との打ち合わせのタイミング**で、フルネススタッフもアンケート結果についての確認をリマインドする

### 改善案２
* ラーニングツリー側の事務局の方からも、2日目の朝の打ち合わせの際に、リクエストを確認されている場合は、直接リマインドいただくように相談・交渉する

**Comment by imagepit** [comment]
ご提案ありがとうございます。改善案について問題ありません。
こちら側としてはあまり運用の手間を増やしても欲しくないのでチェックシートにわかりやすく工夫してもらうだけでも大丈夫ですので、稼働バランスに合わせて対応頂ければと思います。

**Comment by MinamiSakamotoIppei** [comment]
チェックシートでの表現を以下のように修正いたしました。
https://notepm.jp/sharing/772179cd-5f06-458b-8156-a22159e3bed1
より理解しやすくなるアイディアがあれば、ご指摘ください。

研修前にはチェックシートを必ずご確認いただき、
安心してご準備いただけるシートの品質向上に努めます。

<img width="835" alt="スクリーンショット 2024-12-24 12 05 56" src="https://github.com/user-attachments/assets/3ff4afbe-4cb1-4c89-afbf-f5e82a2722c0" />

**Comment by imagepit** [comment]
ご連絡ありがとうございます。チェックシートが改善されていることを確認しまいた。問題ないと思います！
それでは本件は一旦クローズいたします。
